### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by daviramoncl** [NanderTGA/windows96-local-2.0#3]
when i tried node rofs downloader.ts it didnt work the error: 
C:\Users\noonie\windows96-local-2.0-main>node rofs.downloader.ts
node:internal/modules/cjs/loader:1093
  throw err;
  ^

Error: Cannot find module 'C:\Users\noonie\windows96-local-2.0-main\rofs.downloa
der.ts'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_ma
in:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v19.7.0

C:\Users\noonie\windows96-local-2.0-main>

**Comment by daviramoncl** [comment]
Also im noonie (another)#4299

**Comment by daviramoncl** [comment]
and im Windows8 from msgroom

**Comment by NanderTGA** [comment]
You got the filename wrong, it's supposed to be `node "rofs downloader.js"` as said in the readme.
Please also make sure to run `npm install` and `npx tsc` first.
